function(print_debug_vars)
    message("Root source dir: ${CMAKE_SOURCE_DIR}")
    message("Root build dir: ${CMAKE_BINARY_DIR}")
    message("Current source dir: ${CMAKE_CURRENT_SOURCE_DIR}")
    message("Current build dir: ${CMAKE_CURRENT_BINARY_DIR}")
endfunction()
