function(enable_doxygen)
    option(ENABLE_DOXYGEN "Build doxygen documentation from sources" ON)
    if(ENABLE_DOXYGEN)
        set(DOXYGEN_CALLER_GRAPH ON)
        set(DOXYGEN_CALL_GRAPH ON)
        set(DOXYGEN_EXTRACT_ALL ON)
        find_package(Doxygen REQUIRED dot)
        doxygen_add_docs(docs ${CMAKE_SOURCE_DIR})
    endif()
endfunction()
